defaults: &defaults
  domain: <%= ENV['CANONICAL_HOST'] %>
  protocol: <%= ENV['CANONICAL_PROTOCOL'] || 'http://' %>
  port: <%= ENV['RACK_ENV'] == 'development' ? ENV['CANONICAL_PORT'] : nil %>
  sentry:
    dsn: <%= ENV['SENTRY_DSN'] %>
  github:
    client_id: <%= ENV['GITHUB_CLIENT_ID'] %>
    client_secret: <%= ENV['GITHUB_CLIENT_SECRET'] %>
  secret_token: <%= ENV['SECRET_TOKEN'] %>
  google_analytics:
    tracker: <%= ENV['GOOGLE_ANALYTICS_TRACKER'] %>
    domain: <%= ENV['GOOGLE_ANALYTICS_DOMAIN'] %>

development:
  <<: *defaults

staging:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
